name: Unit tests for Pylint

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on:
      - self-hosted
      - linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check last step status
        run: echo "Test Flake8" && python3.9 -m flake8 tennis.py
