name: Unit tests for Pylint

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on:
      - self-hosted
      - linter
    steps:
      - uses: actions/checkout@v2

      - name: Check last step status
        run: |
          echo "Test Flake8"
          python -m flake8 *.py
